from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('modify_category/<int:category_id>/', views.modify_category, name='modify_category'),
    path('contact_us', views.contact_us, name='contact_us'),
    path('success_pay', views.success_pay, name='success_pay'),
    path('<str:category_title>/filter/', views.filter_videos, name='filter'),
    path('purchage_page/', views.purchage_page, name='nav'),
    path('purchage/', views.purchage, name='none'),
    path('verify_access/<int:creator_id>/<int:video_id>/<int:step_id>/', views.verify_access, name='center'),
    path('video/<int:video_id>/', views.watch_video, name='watch_video'),
    path('watch_next_video/<int:video_id>/', views.watch_next_video, name='watch_next_video'),
    path('watch_prev_video/<int:video_id>/', views.watch_prev_video, name='watch_prev_video'),
    path('tuto_step/<int:video_id>/<int:step_id>/', views.watch_step, name='tuto_step'),
    path('watch_next_step/<int:video_id>/<int:step_id>/', views.watch_next_step, name='watch_next_step'),
    path('watch_prec_step/<int:video_id>/<int:step_id>/', views.watch_prec_step, name='watch_prec_step'),
    path('video/add_comment/', views.add_comment, name='add_comment'),
    path('video/add_report/', views.add_report, name='add_report'),
    path('video/add_like/<int:video_id>/', views.add_like, name='add_like'),
    path('<str:session_username>/profile/', views.profile, name='profile'),
    path('<str:session_username>/dashboard/', views.dashboard, name='dashboard'),
    path('add_subscriber/<viewer>/', views.add_sub, name='add_subscriber'),
    path('upload/', views.upload_video, name='upload'),
    path('add_category/', views.add_category, name='add_category'),
    path('upload_step/<int:video_id>/', views.upload_step, name='upload_step'),
    path('edit_video/<int:video_id>', views.edit_video, name='edit_video'),
    path('delete_video/', views.delete_video, name='delete_video'),
    path('delete_categ/', views.delete_categ, name='delete_categ'),
    path('delete_step/', views.delete_step, name='delete_step'),
    path('list_reports/', views.list_reports, name='list_reports'),
    path('list_categories/', views.list_categories, name='list_categories'),
    path('list_messages/', views.list_messages, name='list_messages'),
    path('list_creators/', views.list_creators, name='list_creators'),
    path('update_details/', views.update_details, name='update_details'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('search_video/', views.search_video, name='search_video'),
    path('search/', views.search, name='search'),
]