# Generated by Django 2.2.10 on 2021-08-09 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('letsgo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('video_file', models.FileField(upload_to='videos/steps')),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('likes', models.ManyToManyField(related_name='like', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letsgo.VideoPost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video_views', models.ManyToManyField(related_name='video_view', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
