# Generated by Django 2.2.10 on 2021-08-17 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letsgo', '0004_auto_20210817_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopost',
            name='thumbnail',
            field=models.ImageField(default='none', upload_to='videos/thumbnail/'),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='video_file',
            field=models.FileField(upload_to='videos'),
        ),
    ]
