# Generated by Django 2.2.10 on 2021-08-17 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letsgo', '0006_auto_20210817_0619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesstuto',
            old_name='accessTuto_date',
            new_name='date',
        ),
    ]
