# Generated by Django 2.2.10 on 2021-08-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letsgo', '0009_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstuto',
            name='creator_name',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
    ]
