# Generated by Django 3.2.6 on 2021-09-09 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('letsgo', '0011_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='letsgo.category'),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='videos/thumbnail/'),
        ),
    ]
