# Generated by Django 3.2.6 on 2021-09-13 14:46

from django.db import migrations, models
import letsgo.models


class Migration(migrations.Migration):

    dependencies = [
        ('letsgo', '0012_auto_20210909_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='videopost',
            name='any_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='video_file',
            field=models.FileField(upload_to=letsgo.models.user_directory_path),
        ),
    ]
